version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "heavenms"
    ports: 
      - 3306:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
